// web/components/Counter.vue
<template>
	<div>
		<div
			class="flex justify-center text-6xl time"
		>{{displayMinutes}}:{{displaySeconds}}.{{displayMilliseconds}}</div>
		<div class="flex flex-col mt-4 buttons">
			<a
				v-if="timerStarted"
				class="flex justify-center w-24 w-full py-4 mb-4 transition-colors duration-300 bg-gray-400 border border-gray-400 rounded-lg shadow-lg cursor-pointer hover:bg-gray-300"
				@click="pauseTimer()"
			>Pause</a>
			<a
				v-else
				class="flex justify-center w-24 w-full py-4 mb-4 transition-colors duration-300 bg-gray-400 border border-gray-400 rounded-lg shadow-lg cursor-pointer hover:bg-gray-300"
				@click="showRemaining()"
			>Start</a>
			<a
				class="flex justify-center w-24 w-full py-4 mb-4 transition-colors duration-300 bg-gray-400 border border-gray-400 rounded-lg shadow-lg cursor-pointer hover:bg-gray-300"
				@click="clearTimer()"
			>Clear</a>
		</div>
	</div>
</template>

<script>
export default {
	props: {
		startTime: {
			type: Number,
			default: 1800000,
		},
	},
	data: () => ({
		displayMinutes: "00",
		displaySeconds: "00",
		displayMilliseconds: 0,
		timer: null,
		timeLeft: 0,
		timerStarted: false,
	}),
	watch: {
		startTime(newValue, oldValue) {
			this.setTime(newValue)
		},
	},
	mounted() {
		this.setTime(this.startTime)
	},
	beforeDestroy() {
		this.clearTimer()
	},
	methods: {
		setTime(value) {
			this.displayMinutes = this.formatNum(
				Math.floor((value % this._hours) / this._minutes),
			)
			this.displaySeconds = this.formatNum(
				Math.floor((value % this._minutes) / this._seconds),
			)
			this.displayMilliseconds = 0
			this.timeLeft = value
		},
		formatNum: num => (num < 10 ? `0${num}` : num),
		showRemaining() {
			if (this.timerStarted) return
			this.timer = setInterval(() => {
				this.timerStarted = true
				const distance = this.timeLeft

				if (distance < 0) return clearInterval(this.timer)

				const minutes = Math.floor((distance % this._hours) / this._minutes)
				const seconds = Math.floor((distance % this._minutes) / this._seconds)
				const milliseconds = Math.floor(
					(distance % this._seconds) / this._milliseconds,
				)

				this.displayMinutes = this.formatNum(minutes)
				this.displaySeconds = this.formatNum(seconds)
				this.displayMilliseconds = milliseconds

				this.timeLeft = this.timeLeft - 100
			}, 100)
		},
		pauseTimer() {
			this.timerStarted = false
			clearInterval(this.timer)
		},
		clearTimer() {
			this.timerStarted = false
			this.timeLeft = this.startTime
			clearInterval(this.timer)
			this.setTime(this.startTime)
		},
	},
	computed: {
		_milliseconds: () => 100,
		_seconds: () => 1000,
		_minutes() {
			return this._seconds * 60
		},
		_hours() {
			return this._minutes * 60
		},
		_days() {
			return this._hours * 24
		},
		end() {
			return new Date(
				this.year,
				this.month,
				this.date,
				this.hour,
				this.minute,
				this.second,
				this.millisecond,
			)
		},
	},
}
</script>

<style lang="scss" scoped>
</style>

// react-web/src/components/Counter.jsx
import { useState, useEffect, useRef } from 'react';

export default function Counter({ startTime = 1800000 }) {
	const [displayMinutes, setDisplayMinutes] = useState('00');
	const [displaySeconds, setDisplaySeconds] = useState('00');
	const [displayMilliseconds, setDisplayMilliseconds] = useState(0);
	const [timeLeft, setTimeLeft] = useState(startTime);
	const [timerStarted, setTimerStarted] = useState(false);
	const timerRef = useRef(null);

	const _milliseconds = 100;
	const _seconds = 1000;
	const _minutes = _seconds * 60;
	const _hours = _minutes * 60;

	const formatNum = (num) => (num < 10 ? `0${num}` : num);

	const setTime = (value) => {
		setDisplayMinutes(formatNum(Math.floor((value % _hours) / _minutes)));
		setDisplaySeconds(formatNum(Math.floor((value % _minutes) / _seconds)));
		setDisplayMilliseconds(0);
		setTimeLeft(value);
	};

	const showRemaining = () => {
		if (timerStarted) return;
		
		timerRef.current = setInterval(() => {
			setTimerStarted(true);
			
			setTimeLeft((prevTimeLeft) => {
				const distance = prevTimeLeft;

				if (distance < 0) {
					clearInterval(timerRef.current);
					return prevTimeLeft;
				}

				const minutes = Math.floor((distance % _hours) / _minutes);
				const seconds = Math.floor((distance % _minutes) / _seconds);
				const milliseconds = Math.floor((distance % _seconds) / _milliseconds);

				setDisplayMinutes(formatNum(minutes));
				setDisplaySeconds(formatNum(seconds));
				setDisplayMilliseconds(milliseconds);

				return prevTimeLeft - 100;
			});
		}, 100);
	};

	const pauseTimer = () => {
		setTimerStarted(false);
		if (timerRef.current) {
			clearInterval(timerRef.current);
		}
	};

	const clearTimer = () => {
		setTimerStarted(false);
		if (timerRef.current) {
			clearInterval(timerRef.current);
		}
		setTime(startTime);
	};

	useEffect(() => {
		setTime(startTime);
	}, [startTime]);

	useEffect(() => {
		return () => {
			if (timerRef.current) {
				clearInterval(timerRef.current);
			}
		};
	}, []);

	return (
		<div>
			<div className="flex justify-center text-6xl time">
				{displayMinutes}:{displaySeconds}.{displayMilliseconds}
			</div>
			<div className="flex flex-col mt-4 buttons">
				{timerStarted ? (
					<a
						className="flex justify-center w-24 w-full py-4 mb-4 transition-colors duration-300 bg-gray-400 border border-gray-400 rounded-lg shadow-lg cursor-pointer hover:bg-gray-300"
						onClick={pauseTimer}
					>
						Pause
					</a>
				) : (
					<a
						className="flex justify-center w-24 w-full py-4 mb-4 transition-colors duration-300 bg-gray-400 border border-gray-400 rounded-lg shadow-lg cursor-pointer hover:bg-gray-300"
						onClick={showRemaining}
					>
						Start
					</a>
				)}
				<a
					className="flex justify-center w-24 w-full py-4 mb-4 transition-colors duration-300 bg-gray-400 border border-gray-400 rounded-lg shadow-lg cursor-pointer hover:bg-gray-300"
					onClick={clearTimer}
				>
					Clear
				</a>
			</div>
		</div>
	);
}
