// apps/web/src/components/layout/FooterNav.jsx
import { useState } from 'react'
import { Link, useLocation } from 'react-router-dom'
import PRIcons from '../PRIcons'
import DarkModeToggle from '../DarkModeToggle'
import { isAdminMode } from '../../utils/adminMode'
import './FooterNav.scss'

const FooterNav = () => {
	const [menuOpen, setMenuOpen] = useState(false)
	const location = useLocation()

	const adminEnabled = isAdminMode()

	const menu = [
		{
			title: "Home",
			to: "/",
			icon: "home",
			nuxt: true,
		},
		{
			title: "Rulebooks",
			to: "/rulebooks",
			icon: "rules",
			nuxt: true,
		},
		{
			title: "All Rangers",
			to: "/all-rangers",
			icon: "morpher",
			nuxt: true,
		},
		{
			title: "Randomizer",
			to: "/randomizer",
			icon: "pr-hotg",
			nuxt: true,
		},
		{
			title: "Dice Roller",
			to: "/dice",
			icon: "pr-hotg",
			nuxt: true,
		},
		{
			title: "Token Tracker",
			to: "/tokens",
			icon: "pr-hotg",
			nuxt: true,
		},
		...(adminEnabled ? [{
			title: "Admin",
			to: "/admin",
			icon: "pr-hotg",
			nuxt: true,
		}] : []),
	]

	const nuxtLinks = menu.filter(item => item.nuxt)
	const version = __APP_VERSION__

	return (
		<div>
			<nav className="nav desktop dark:bg-gray-900 dark:border-purple-600">
				<div className="flex flex-wrap flex-1 md:flex-col md:w-full">
					{nuxtLinks.map(link => (
						<Link 
							key={link.to} 
							to={link.to} 
							className={`nav__link dark:hover:bg-gray-800 ${location.pathname === link.to ? 'active dark:bg-gray-800 dark:text-purple-400' : ''}`}
						>
							<PRIcons icon={link.icon} />
							<span className="pt-2 text-sm capitalize">{link.title}</span>
						</Link>
					))}
				</div>
				<div className="flex flex-col gap-2 items-center mb-4">
					<DarkModeToggle />
				</div>
				<span className="absolute bottom-0 left-0 px-4 py-6 text-sm text-gray-300 dark:text-gray-500">v{version}</span>
			</nav>
			<a onClick={() => setMenuOpen(!menuOpen)} className={`nav__link dark:bg-gray-800 dark:border-purple-600 ${menuOpen ? 'open' : ''}`} id="home-link">
				<PRIcons />
				<span className="hidden text-sm capitalize md:block">Menu</span>
			</a>
			{menuOpen && (
				<div className={`nav__transition ${menuOpen ? 'nav__transition--enter' : 'nav__transition--leave'}`}>
					<nav
						className={`nav mobile dark:bg-gray-900 dark:border-purple-600 ${menuOpen ? 'open' : 'closed'}`}
						onClick={() => setMenuOpen(false)}
					>
						<div className="flex flex-wrap flex-1 md:flex-col md:w-full">
							{nuxtLinks.map(link => (
								<Link 
									key={link.to} 
									to={link.to} 
									className={`nav__link dark:hover:bg-gray-800 ${location.pathname === link.to ? 'active dark:bg-gray-800 dark:text-purple-400' : ''}`}
								>
									<PRIcons icon={link.icon} />
									<span className="pt-2 text-sm capitalize">{link.title}</span>
								</Link>
							))}
						</div>
						<div className="flex flex-col gap-2 items-center mb-4">
							<DarkModeToggle />
						</div>
						<span className="absolute bottom-0 left-0 px-4 py-6 text-sm text-gray-300 dark:text-gray-500">v{version}</span>
					</nav>
				</div>
			)}
		</div>
	)
}

export default FooterNav

// web/components/layout/FooterNav.vue
<template>
	<div>
		<nav class="nav desktop">
			<div class="flex flex-wrap flex-1 md:flex-col md:w-full">
				<nuxt-link v-for="link in nuxtLinks" :key="link.to" :to="link.to" class="nav__link">
					<PRicon :icon="link.icon" />

					<span class="pt-2 text-sm capitalize">{{ link.title }}</span>
				</nuxt-link>
			</div>
			<span class="absolute bottom-0 left-0 px-4 py-6 text-sm text-gray-300">v{{version}}</span>
		</nav>
		<a @click="menuOpen = !menuOpen" class="nav__link" :class="menuOpen ? 'open' : ''" id="home-link">
			<PRicon />
			<span class="hidden text-sm capitalize md:block">Menu</span>
		</a>
		<transition name="bottomup">
			<nav
				v-if="menuOpen"
				class="nav mobile"
				:class="menuOpen ? 'open' : 'closed'"
				@click="menuOpen = false"
			>
				<div class="flex flex-wrap flex-1 md:flex-col md:w-full">
					<nuxt-link v-for="link in nuxtLinks" :key="link.to" :to="link.to" class="nav__link">
						<PRicon :icon="link.icon" />

						<span class="pt-2 text-sm capitalize">{{ link.title }}</span>
					</nuxt-link>
				</div>
				<span class="absolute bottom-0 left-0 px-4 py-6 text-sm text-gray-300">v{{version}}</span>
			</nav>
		</transition>
	</div>
</template>

<script>
import PRicon from "~/components/PRIcons"
export default {
	components: {
		PRicon,
	},
	data() {
		return {
			menuOpen: false,
			menu: [
				{
					title: "Home",
					to: "/",
					icon: "home",
					nuxt: true,
				},
				{
					title: "Rulebooks",
					to: "/rulebooks",
					icon: "rules",
					nuxt: true,
				},
				{
					title: "All Rangers",
					to: "/all-rangers",
					icon: "morpher",
					nuxt: true,
				},
				// {
				// 	title: "All Teams",
				// 	to: "/all-teams",
				// 	icon: "morpher",
				// 	nuxt: true,
				// },
				{
					title: "Randomizer",
					to: "/randomizer",
					icon: "pr-hotg",
					nuxt: true,
				},
				{
					title: "Dice Roller",
					to: "/dice",
					icon: "pr-hotg",
					nuxt: true,
				},
				{
					title: "Token Tracker",
					to: "/tokens",
					icon: "pr-hotg",
					nuxt: true,
				},
				// {
				// 	title: "Countdown",
				// 	to: "/countdown",
				// 	icon: "pr-hotg",
				// 	nuxt: true,
				// },
			],
		}
	},
	computed: {
		nuxtLinks() {
			return this.menu.filter(item => {
				return item.nuxt
			})
		},
		aLinks() {
			return this.menu.filter(item => {
				return !item.nuxt
			})
		},
		version() {
			return process.env.VERSION_NUMBER
		},
	},
}
</script>

<style lang="scss" scoped>
.nav {
	@apply fixed bottom-0 w-full transition-all h-screen pt-4 border-t-0 duration-500 bg-white border-purple-700 z-40 overflow-y-auto;
	box-shadow: 0 16px 0 0 theme("colors.purple.700") inset;
	scrollbar-width: none;
	&::-webkit-scrollbar {
		width: 0px;
	}
	&.desktop {
		@apply hidden;
	}

	&__link {
		@apply flex flex-col flex-grow items-center justify-center overflow-hidden whitespace-nowrap text-sm transition-colors duration-100 ease-in-out py-4 w-1/2;
		&:hover {
			@apply bg-gray-100;
		}

		&#home-link {
			@apply fixed border-purple-700 shadow-lg rounded-full bg-white transition-all h-20 w-20 flex items-center justify-center duration-500 z-50;
			left: 50%;
			bottom: 24px;
			transform: translateX(-50%);
			// width: 77px;
			&.open {
				@apply bg-gray-200;
				box-shadow: 0 0 0 8px theme("colors.purple.700");
			}
		}
	}
	@media screen and (min-width: theme("screens.md")) {
		@apply h-full left-0 top-0 rounded-r-lg rounded-l-none flex-col justify-start w-32 border-r-8 border-t-0;
		box-shadow: none;

		&.desktop {
			@apply flex;
		}

		&__link {
			@apply flex-grow-0 w-full;
			&#home-link {
				@apply hidden;
			}
		}
	}
}

.nuxt-link-exact-active {
	@apply bg-gray-200 text-purple-600;
}
</style>
