// react-web/src/pages/Team.jsx
import { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { useApp } from '../context/AppContext';
import RangerCard from '../components/cards/RangerCard';
import sanity from '../lib/sanityClient';

export default function Team() {
	const { team: teamParam } = useParams();
	const { setLoadingState } = useApp();
	const [team, setTeam] = useState('');
	const [rangers, setRangers] = useState([]);

	useEffect(() => {
		const fetchData = async () => {
			const query = `*[_type == 'team' && slug.current == '${teamParam}'] {
				name,
				"rangers": *[_type == 'ranger' && rangerInfo.team._ref == ^._id] | order(rangerInfo.order asc) {
					_id,
					name,
					rangerInfo {
						...,
						'color': color.title,
						'slug': slug.current,
						'team': team->name,
						'teamPosition': teamPosition.current
					},
					rangerCards {
						...,
						'image': image.asset->url,
					}
				}
			}[0]`;

			const data = await sanity.fetch(query);

			setTeam(data?.name || '');
			setRangers(data?.rangers || []);

			setTimeout(() => setLoadingState(false), 500);
		};

		fetchData();
	}, [teamParam, setLoadingState]);

	const friendlyURL = (text) => {
		return text.toLowerCase().replace(' ', '-');
	};

	return (
		<div className="flex flex-col">
			<h2>
				{team}
				<br />
				Power Rangers
			</h2>
			<div className="flex flex-wrap justify-around -mx-3" id="rangersTeam">
				{rangers.map((ranger, i) => (
					<Link
						key={ranger._id}
						className={`no-underline px-3 py-6 md:px-6 w-1/2 flex ${
							i % 2 === 0 ? 'justify-end' : 'justify-start'
						}`}
						to={`/${friendlyURL(team + '/' + ranger.rangerInfo.slug)}`}
					>
						<RangerCard className="lg:max-w-lg" noDesc ranger={ranger} sanity />
					</Link>
				))}
			</div>
		</div>
	);
}

// web/pages/_team/index.vue
<template>
	<div class="flex flex-col">
		<nuxt-child v-if="$route.params.ranger" />
		<h2>
			{{team}}
			<br />Power Rangers
		</h2>
		<div class="flex flex-wrap justify-around -mx-3" id="rangersTeam">
			<nuxt-link
				v-for="(ranger, i) in rangers"
				:key="i"
				:class="`no-underline px-3 py-6 md:px-6 w-1/2 flex ${
					i % 2 == 0 ? 'justify-end' : 'justify-start'
				}`"
				:to="`/${$friendlyURL(team + '/' + ranger.rangerInfo.slug)}`"
			>
				<RangerCard class="lg:max-w-lg" noDesc :ranger="ranger" sanity />
			</nuxt-link>
		</div>
		<!-- #rangersTeam -->
	</div>
	<!-- root -->
</template>

<script>
import RangerCard from "~/components/cards/RangerCard"
import { mapGetters } from "vuex"

export default {
	name: "RangerTeam",
	components: {
		RangerCard,
	},
	data() {
		return {
			team: "",
			rangers: [],
		}
	},
	watch: {
		$route(newValue, oldValue) {
			this.fetchData()
		},
	},
	mounted() {
		this.fetchData()
	},
	methods: {
		async fetchData() {
			const { $store, $route, $sanityClient } = this
			let teamRangersFetch = await $sanityClient.fetch(
				this.$getQuery("teamRangers", $route.params.team),
			)
			this.rangers = teamRangersFetch.rangers
			this.team = teamRangersFetch.name
			setTimeout(() => $store.commit("setLoadingState", false), 500)
		},
	},
}
</script>

<style lang="scss" scoped></style>
