// web/pages/_team/index/_ranger.vue
<template>
	<div v-if="ranger" class="max-w-3xl mx-auto mt-6 ranger">
		<RangerCard class="mb-10" :ranger="ranger" single />

		<div v-if="ranger.rangerCards.deck.length" class="mb-10">
			<h2>Deck</h2>
			<div v-for="card in ranger.rangerCards.deck" :key="card._key">
				<RangerDeckSingle :card="card" />
			</div>
		</div>

		<div v-if="ranger.rangerCards.zords.length" class="mb-10">
			<h2>Zords</h2>
			<div v-for="zord in ranger.rangerCards.zords" :key="zord._key">
				<h3>{{zord.name}}</h3>
				<p>{{zord.ability}}</p>
			</div>
		</div>

		<!-- TODO: Better similar query -->
		<!-- <div v-if="similar.length">
			<h2>Similar Rangers</h2>
			<div class="flex flex-wrap">
				<nuxt-link
					v-for="(item, i) in similar"
					:key="i"
					:to="`/${$route.params.team}/${item.slug}`"
					:class="`p-6 shadow-lg rounded-lg my-4 mr-4 ${$getColor(
					item.color.title,
				)} text-white flex flex-col`"
				>
					<span>{{ item.name }}</span>
					<span>{{ item.teamPosition[0] == '*' ? item.teamPosition.replace(/\*/g, '') : `${item.teamPosition.replace(/-/g, '')} Ranger` }}</span>
				</nuxt-link>
			</div>
		</div>-->
	</div>
</template>

<script>
import RangerCard from "~/components/cards/RangerCard"
import RangerDeckSingle from "~/components/cards/RangerDeckSingle"
import { mapGetters } from "vuex"

export default {
	name: "Ranger",
	scrollToTop: true,
	components: {
		RangerCard,
		RangerDeckSingle,
	},
	data() {
		return {
			ranger: null,
			similar: [],
			contentRanger: null,
		}
	},
	watch: {
		$route(newValue, oldValue) {
			this.fetchData()
		},
	},
	mounted() {
		this.fetchData()
	},
	methods: {
		async fetchData() {
			const { $store, $route, $sanityClient } = this
			let currentRangerFetch = await $sanityClient.fetch(
				this.$getQuery("singleRanger", $route.params.ranger),
			)

			this.ranger = currentRangerFetch
			this.similar = currentRangerFetch.similar

			setTimeout(() => $store.commit("setLoadingState", false), 500)
		},
	},
	computed: {
		similarWOCurrent() {
			return (
				this.similar.filter(ranger => {
					return ranger.rangerInfo.slug != this.$route.params.ranger
				}) || []
			)
		},
	},
}
</script>

<style lang="scss" scoped>
.ranger {
	animation: 1s appear;
}
</style>

// react-web/src/pages/Ranger.jsx
import { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import { useApp } from '../context/AppContext';
import RangerCard from '../components/cards/RangerCard';
import RangerDeckSingle from '../components/cards/RangerDeckSingle';
import sanity from '../lib/sanityClient';

export default function Ranger() {
	const { ranger: rangerParam } = useParams();
	const { setLoadingState } = useApp();
	const [ranger, setRanger] = useState(null);

	useEffect(() => {
		const fetchData = async () => {
			const query = `*[_type == 'ranger' && rangerInfo.slug.current == '${rangerParam}'] {
				_id,
				name,
				rangerInfo {
					...,
					'color': color.title,
					'slug': slug.current,
					'team': team->name,
					'teamPosition': teamPosition.current
				},
				rangerCards {
					...,
					'image': image.asset->url,
					zords[]->
				},
				'deck': Deck[]
			}[0]`;

			const data = await sanity.fetch(query);

			setRanger(data);

			setTimeout(() => setLoadingState(false), 500);
		};

		fetchData();
	}, [rangerParam, setLoadingState]);

	if (!ranger) {
		return null;
	}

	return (
		<div className="max-w-3xl mx-auto mt-6 ranger">
			<RangerCard className="mb-10" ranger={ranger} single />

			{ranger.rangerCards?.deck?.length > 0 && (
				<div className="mb-10">
					<h2>Deck</h2>
					{ranger.rangerCards.deck.map((card) => (
						<RangerDeckSingle key={card._key} card={card} />
					))}
				</div>
			)}

			{ranger.rangerCards?.zords?.length > 0 && (
				<div className="mb-10">
					<h2>Zords</h2>
					{ranger.rangerCards.zords.map((zord) => (
						<div key={zord._key || zord._id}>
							<h3>{zord.name}</h3>
							<p>{zord.ability}</p>
						</div>
					))}
				</div>
			)}
		</div>
	);
}
