// web/components/gameComponents/Die.vue
<template>
	<div
		class="flex items-center justify-center border border-gray-400 rounded-lg shadow-lg w-14 h-14 md:w-20 md:h-20"
	>{{symbol}}</div>
</template>

<script>
export default {
	props: {
		number: {
			type: [Number, String],
			default: 1,
		},
	},
	computed: {
		symbol() {
			let symbol
			if (this.number == 1 || this.number == 6) symbol = "O"
			if (this.number == 2 || this.number == 4 || this.number == 5) symbol = "X"
			if (this.number == 3) symbol = "X X"
			return symbol
		},
	},
}
</script>

<style lang="scss" scoped>
</style>

// react-web/src/components/gameComponents/Die.jsx
export default function Die({ number = 1 }) {
	const getSymbol = () => {
		const num = typeof number === 'string' ? parseInt(number) : number;
		
		if (num === 1 || num === 6) return 'O';
		if (num === 2 || num === 4 || num === 5) return 'X';
		if (num === 3) return 'X X';
		
		return 'O';
	};

	return (
		<div className="flex items-center justify-center border border-gray-400 rounded-lg shadow-lg w-14 h-14 md:w-20 md:h-20">
			{getSymbol()}
		</div>
	);
}
