// web/components/EnemyCard.vue
<template>
	<div
		class="w-full shadow-lg border border-gray-400 rounded-lg overflow-hidden"
	>
		<div :class="`h-48 flex-none  ${$getColor(color)}`"></div>
		<div
			class="bg-white p-4 flex flex-col justify-between leading-normal w-full"
		>
			<span class="">
				<p class="text-md font-bold text-gray-900 items-center uppercase">
					{{ enemy.name }}
				</p>
				<p class="text-sm text-gray-600 flex items-center">
					{{ enemy.expansion }}
				</p>
			</span>
		</div>
	</div>
</template>

<script>
export default {
	name: "EnemyCard",
	props: {
		enemy: {
			type: Object,
			default: { name: "", teamPosition: "", abilityName: "", abilityDesc: "" },
		},
		color: {
			type: String,
		},
	},
	methods: {},
}
</script>

<style lang="scss" scoped></style>

// react-web/src/components/cards/EnemyCard.jsx
export default function EnemyCard({ enemy, type = 'foot soldier' }) {
	const getEnemyColor = () => {
		switch (type.toLowerCase()) {
			case 'monster':
				return 'bg-orange-400';
			case 'master':
				return 'bg-pink-800';
			default:
				return 'bg-lime-300';
		}
	};

	return (
		<div className="w-full overflow-hidden border card lg:flex">
			<div className={`lg:h-auto lg:w-48 flex-none ${getEnemyColor()}`}>
				{enemy?.image && (
					<img
						className="p-4 mx-auto max-h-48 md:full"
						src={`${enemy.image}?h=150`}
						alt={enemy.name}
					/>
				)}
			</div>

			<div className="flex flex-col justify-between w-full leading-normal bg-white content md:p-4">
				<span>
					<p className="items-center font-bold text-gray-900 uppercase text-md">
						{enemy?.name}
					</p>
				</span>
			</div>
		</div>
	);
}
