// web/components/RangerCard.vue
<template>
	<div class="w-full overflow-hidden border border-gray-400 rounded-lg shadow-lg lg:flex">
		<div :class="`h-48 lg:h-auto lg:w-48 flex-none  ${$getColor(rangerColor)}`"></div>
		<div class="flex flex-col justify-between w-full p-3 leading-normal bg-white md:p-4">
			<span class>
				<p class="items-center font-bold text-gray-900 uppercase text-md">{{ ranger.name }}</p>
				<p class="flex items-center text-sm text-gray-600">{{ teamPosition }}</p>
				<div class="mb-2 text-xl font-bold text-gray-900">{{ ranger.abilityName }}</div>
				<p v-if="!noDesc" class="text-base text-gray-700">{{ ranger.abilityDesc }}</p>
			</span>
		</div>
	</div>
</template>

<script>
export default {
	name: "RangerCard",
	props: {
		ranger: {
			type: Object,
			default: {
				name: "",
				teamPosition: "",
				abilityName: "",
				abilityDesc: "",
				color: "",
			},
		},
		noDesc: {
			type: Boolean,
			default: false,
		},
		sanity: {
			type: Boolean,
			default: false,
		},
	},
	methods: {},
	computed: {
		rangerColor() {
			if (this.sanity) {
				return this.ranger.color.title.toLowerCase() || ""
			}
			return this.ranger.color
		},
		teamPosition() {
			if (this.sanity) {
				return `${this.ranger.team} ${this.ranger.color.title}`
			}
			return this.ranger.teamPosition
		},
	},
}
</script>

<style lang="scss" scoped></style>

// react-web/src/components/cards/RangerCard.jsx
import { getColor } from '../../utils/helpers';
import './RangerCard.css';

export default function RangerCard({ ranger, noDesc = false, single = false, className = '' }) {
	const rangerColor = ranger?.rangerInfo?.color || '';
	const teamPosition = ranger?.rangerInfo?.teamPosition || '';
	
	// Format team position text
	const formatTeamPosition = (position) => {
		if (!position) return '';
		return position[0] === '*' 
			? position.replace(/\*/g, '') 
			: `${position.replace(/-/g, '')} Ranger`;
	};

	// Build custom classes
	const getCustomClasses = () => {
		const classes = [];
		
		if (single) classes.push('single');
		if (!ranger?.rangerCards?.image) classes.push('custom-height');
		
		classes.push(getColor(rangerColor));
		
		return classes.join(' ');
	};

	return (
		<div className={`w-full overflow-hidden border card ${single ? 'sm:flex' : 'md:flex'} ${className}`}>
			<div className={`ranger__image ${getCustomClasses()}`}>
				{ranger?.rangerCards?.image && (
					<img
						className="p-4 rounded-full max-h-48"
						src={`${ranger.rangerCards.image}?h=${single ? '200' : '125'}`}
						alt={ranger.name}
					/>
				)}
			</div>

			<div
				className={`flex flex-col justify-between w-full leading-normal bg-white content ${
					single ? 'sm:p-2' : 'md:p-4'
				}`}
			>
				<span>
					<p className="items-center font-bold text-gray-900 uppercase text-md">
						{ranger?.name}
					</p>
					<p className="flex items-center text-sm text-gray-600">
						{formatTeamPosition(teamPosition)}
					</p>
					<div className="mb-2 text-xl font-bold text-gray-900">
						{ranger?.rangerCards?.abilityName}
					</div>
					{!noDesc && (
						<p className="text-base text-gray-700">
							{ranger?.rangerCards?.abilityDesc}
						</p>
					)}
				</span>
			</div>
		</div>
	);
}
