// web/components/cards/EnemyCard.vue
<template>
	<div class="w-full overflow-hidden border card lg:flex">
		<div :class="`lg:h-auto lg:w-48 flex-none  ${enemyColor}`">
			<img class="p-4 mx-auto max-h-48 md:full" v-if="enemy.image" :src="`${enemy.image}?h=150`" />
		</div>

		<div class="flex flex-col justify-between w-full leading-normal bg-white content md:p-4">
			<span class>
				<p class="items-center font-bold text-gray-900 uppercase text-md">{{ enemy.name }}</p>
			</span>
		</div>
	</div>
</template>

<script>
export default {
	name: "RangerCard",
	props: {
		enemy: {
			type: Object,
			default: {
				name: "",
				teamPosition: "",
				abilityName: "",
				abilityDesc: "",
				color: "",
			},
		},
		type: {
			type: String,
			default: "foot soldier",
		},
	},
	methods: {},
	computed: {
		enemyColor() {
			switch (this.type.toLowerCase()) {
				case "monster":
					return "bg-orange-400"
				case "master":
					return "bg-pink-800"

				default:
					return "bg-lime-300"
			}
			return this.enemy.color
		},
	},
}
</script>

<style lang="scss" scoped></style>

// apps/web/src/components/cards/EnemyCard.jsx
export default function EnemyCard({ enemy, type = 'foot soldier' }) {
	const getEnemyColor = () => {
		switch (type.toLowerCase()) {
			case 'monster':
				return 'bg-orange-400';
			case 'master':
				return 'bg-pink-800';
			default:
				return 'bg-lime-300';
		}
	};

	return (
		<div className="w-full overflow-hidden border card lg:flex">
			<div className={`lg:h-auto lg:w-48 flex-none flex items-center justify-center min-h-[12rem] ${getEnemyColor()}`}>
				{enemy?.image && (
					<img
						className="p-4 mx-auto max-h-48 md:full"
						src={`${enemy.image}?h=150`}
						alt={enemy.name}
					/>
				)}
			</div>

			<div className="flex flex-col justify-between w-full leading-normal bg-white content md:p-4">
				<span>
					<p className="items-center font-bold text-gray-900 uppercase text-md">
						{enemy?.name}
					</p>
				</span>
			</div>
		</div>
	);
}
